#!/bin/sh

# Couchbase Server start script. 

set -e

if [ "$1" = 'couchbase-server' ]
then

    if [ "$(id -u)" != "0" ]; then
        echo "This script must be run as root"
        exit 1
    fi

    # Create directories where couchbase stores its data
    cd /opt/couchbase
    mkdir -p var/lib/couchbase \
        var/lib/couchbase/config \
        var/lib/couchbase/data \
        var/lib/couchbase/stats \
        var/lib/couchbase/logs \
        var/lib/moxi
    chown -R couchbase:couchbase var

    nohup /usr/local/bin/couchbase-start init &

    # Start couchbase
    echo "Starting Couchbase Server -- Web UI available at http://<ip>:8091"
    echo "kill all monkeys"
    echo $@
    exec gosu couchbase "$@" 
elif [ "$1" = 'init' ]
then

sleep 30
/opt/couchbase/bin/couchbase-cli cluster-init -c localhost:8091 --cluster-username=admin --cluster-password=oogway --cluster-ramsize=1024 > /tmp/start.log
fi

exec "$@"
